### PR TITLE
Missing VXLAN properties and fix wrong IP addresses

### PR DESCRIPTION
**Pull request by ffmancera**

### CODE REVIEW

**Comment by ffmancera** [comment]
This is related to #123

**Comment by ffmancera** [comment]
@little-dude @gabrik

**Comment by gabrik** [comment]
Great! Indeed using a `Vec<u8>` the check on the endianness can be removed the code becomes easier to understand.
Just a suggestion do a run of `cargo fmt`  and `cargo clippy` before committing so the check will be ok.

**Comment by ffmancera** [comment]
> Great! Indeed using a `Vec<u8>` the check on the endianness can be removed the code becomes easier to understand.
> Just a suggestion do a run of `cargo fmt` and `cargo clippy` before committing so the check will be ok.

Whoops, didn't notice that the project were following rustfmt and cluppy, will do. Thanks!

**Pull request merged**
