### PR TITLE
rtnetlink: Add support of querying qdisc in traffic control

### PR DESCRIPTION
**Pull request by cathay4t**
New function `rtnetlink::Handle::qdisc()` with initial qdisc query
support.

Integration test case added which query the qdisc information of
loopback interface.

### CODE REVIEW

**Comment by cathay4t** [comment]
@little-dude I failed to find example on testing this new handler, do you how should I create the test case for this new functionality?

**Comment by little-dude** [comment]
It would be nice to have an example yes. You can re-use an existing one or create a new one, I don't really have a preference.

**Comment by cathay4t** [comment]
@little-dude Integration test case added which test on qdisc of loopback interface and patch is ready for review.

**Comment by cathay4t** [comment]
Still work in progress and my project need more properties been exposed.

**Pull request merged**
