### PR TITLE
Add preferred source address to rtnetlink route

### PR DESCRIPTION
**Pull request by tsk9**
The PR adds preferred source address to rtnetlink route add() for IPv4 and IPv6.

### CODE REVIEW

**Review by cathay4t — CHANGES_REQUESTED** [review]
Please include an example code so that we can try it locally.

**Comment by tsk9** [comment]
You could test the code like this:
```
sudo ip link add dummy0 type dummy
sudo ip link set dummy0 up
sudo ip addr add 10.0.0.1/16 dev dummy0
sudo ip addr add 10.0.0.2/32 dev dummy0

sudo ./add_route_pref_src 10.0.2.0/24 dummy0 10.0.0.2

sudo ip route show dev dummy0
10.0.0.0/16 proto kernel scope link src 10.0.0.1
10.0.2.0/24 proto static src 10.0.0.2
```

**Comment by cathay4t** [comment]
@tsk9 Thanks for the patch! Please squash three patches into single one. Meanwhile, please also do [git sign-off][1].


[1]: https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for

**Comment by cathay4t** [comment]
Merged. Thanks for the help!

**Comment by cathay4t** [comment]
The CI failure will be fixed by https://github.com/little-dude/netlink/pull/190

**Pull request merged**
