### PR TITLE
netlink-packet-route: implement MacVtap support

### PR DESCRIPTION
**Pull request by ffmancera**
Signed-off-by: Fernando Fernandez Mancera <ffmancera@riseup.net>

### CODE REVIEW

**Comment by ffmancera** [comment]
#123

**Comment by ffmancera** [comment]
@gabrik does this look good to you?

**Comment by gabrik** [comment]
@ffmancera yes, it looks good to me.
Have you tested it on your machine?

**Comment by ffmancera** [comment]
> @ffmancera yes, it looks good to me.
> Have you tested it on your machine?

Yes. I am testing everything using nispor and rtnetlink.

**Pull request merged**
