### PR TITLE
netlink-packet-sock-diag: Add TcpInfo parsing

### PR DESCRIPTION
**Pull request by svart**

### CODE REVIEW

**Review by little-dude — APPROVED** [review]
Thank you for the MR! This was previously removed because the TCP info struct format varies accross kernel versions and/or architectures. To be safe, I think this parsing should only be enabled with `--features=rich_nlas`. See https://github.com/little-dude/netlink/pull/199 which introduced this feature.

**Comment by little-dude** [comment]
Ah sorry I meant to click "request changes", not approve. Seems that I can't change this =/

**Comment by little-dude** [comment]
Oh I just noticed that my comment didn't even go through, sorry @svart :(

I'd like to have this TcpInfo parsing but only with `--features rich-nlas`. See: https://github.com/little-dude/netlink/pull/199

**Review by little-dude — CHANGES_REQUESTED** [review]
Let's make this opt-in via `--features=rich-nlas` just to be safe.

**Comment by svart** [comment]
> Let's make this opt-in via `--features=rich-nlas` just to be safe.

Ok! I will do it right after the holidays.

**Comment by svart** [comment]
> Let's make this opt-in via `--features=rich-nlas` just to be safe.

Uploaded the patch. @little-dude could you please trigger the CI?

**Review by little-dude — APPROVED** [review]

**Comment by little-dude** [comment]
Thanks a lot @svart :) I'll make a release now.

**Comment by little-dude** [comment]
Released 0.4.0!

**Pull request merged**
