### PR TITLE
utils: Optimized calculation align

### PR DESCRIPTION
**Pull request by wllenyj**
Use bitwise operations instead of division.
The length value must be less than `usize::MAX - 4`, otherwise it will
panic. The result is the same as the original logic.

Signed-off-by: wllenyj <wllenyj@linux.alibaba.com>

### CODE REVIEW

**Comment by wllenyj** [comment]
@little-dude   Have some comments for the pr? 
Thanks.

**Comment by wllenyj** [comment]
@little-dude   Have some comments for the pr? 
Thanks.

**Review by little-dude — CHANGES_REQUESTED** [review]
Thanks for this improvement and for adding tests :) This looks great, but could we just rename `RTA` into `NLA` for consistency? I know in the kernel it's called `RTA` and perhaps it was the wrong decision to diverge from that in the first place, but now that we went for `NLA`, I'd rather stay consistent.

**Comment by wllenyj** [comment]
> Thanks for this improvement and for adding tests :) This looks great, but could we just rename `RTA` into `NLA` for consistency? I know in the kernel it's called `RTA` and perhaps it was the wrong decision to diverge from that in the first place, but now that we went for `NLA`, I'd rather stay consistent.

Sure, fixed.
Thank you for review.

**Review by little-dude — APPROVED** [review]
Thanks!

**Pull request merged**
