### PR TITLE
WIP: TC support

### PR DESCRIPTION
**Pull request by MarkPash**
Trying to add TC support to rtnetlink and could use some guidance.
Most of this is adapted from the rest of the code, still new to rust so I don't know best practices/idiomatic code.
So far I have only tested with qdisc messages, and they mostly work. There are nested NLAs that depend on the value of the parent NLA and I don't know how best to approach that.

### CODE REVIEW

**Comment by little-dude** [comment]
Hello! Thanks a lot for your contribution. I'll be back working on this library this week end and next week SO I'll review this within the next few days.


I have to confess that I don't really know `tc`. Would you have a few links or man pages to recommend. The messages don't seem to be documented in the man page, so I assume I'll have to dig through the Linux source?
 
> There are nested NLAs that depend on the value of the parent NLA and I don't know how best to approach that.

Good question. I'll need to look at the code in more details.

**Comment by MarkPash** [comment]
Thank you for taking the time to respond.

The man pages aren't very helpful, it only helps with the tc cli command and I've only been using `tc -s qdisc show` so far for my testing.

In order to find out more about it, the standard methods for figuring out netlink messages still apply, additional information can be found by reading the pyroute2 source code and iproute2 source code.

If you would like to test it, you can simply copy the `dump_links.rs` file in the `rtnetlink` examples and rename to `dump_qdiscs.rs`, replace all mention of `LinkHeader`, `LinkMessage` etc... with `TcHeader` and `TcMessage` and replace `RtnlMessage::GetLink` with `RtnlMessage::GetQueueDiscipline` and it should give you an output similar to the attached file.

`Options` has to be parsed differently based on `Kind`, as the kind is the Queue Discipline and each kind of qdisc has its own unique set of options/tuning knobs, so this is what I need help with figuring out.
The same goes for `StatsApp` as it's the statistics that are unique to that qdisc.
[output.txt](https://github.com/little-dude/netlink/files/2681022/output.txt)

**Comment by little-dude** [comment]
Hi @MarkPash, just letting you know that I haven't forgot about this, but I'd like to land some massive refactoring in https://github.com/little-dude/netlink/pull/2 first. That will conflict a lot with your work, so after the refactoring is merged, I'll rebase your PR and do a proper review. I apologize for taking so long, I know it sucks when your PR is blocked forever, but I think it would be counter productive to ask you to make changes that would be obsoleted by https://github.com/little-dude/netlink/pull/2 anyway.

**Comment by little-dude** [comment]
@MarkPash I ended up merging only a portion of #2 so I'll be able to rebase/review and merge this soon :)

**Comment by little-dude** [comment]
closing in favor of #15

**Pull request closed without merging**
