### PR TITLE
Add infokind and data for wireguard

### PR DESCRIPTION
**Pull request by benjumanji**
Add bare minimum support for creating a wireguard interface without
allocating an extra string.

### CODE REVIEW

**Comment by benjumanji** [comment]
Obviously a better PR would make a `WireguardRequest` struct similar to Vxlan. I can add that in a separate pr later if you don't mind.

**Review by ffmancera — APPROVED** [review]
Hello! Thank you for contributing. I am currently working on wireguard support so do you mind if I take this commit and I complete the rest of the implementation? Thanks!

This needs testing before merging and having a WireguardRequest is a must for this. But as I said, I do have some work on it. Do you mind if I cherry-pick this commit? Author will be kept of course.

**Comment by benjumanji** [comment]
Yeah no problem.

**Comment by benjumanji** [comment]
If it's helpful I do have code already using this to create and tear down interfaces  that could easily be made into a test.

**Comment by ffmancera** [comment]
> If it's helpful I do have code already using this to create and tear down interfaces that could easily be made into a test.

Oh if you would like to share it, it would be nice :-)

A link to the repository or file would be nice, thank you!

**Comment by benjumanji** [comment]
voila.

**Comment by benjumanji** [comment]
I note that ci is now failing... because of the note in the commit: I am sure the test runner doesn't have permissions to create or delete these interfaces.

**Comment by ffmancera** [comment]
> I note that ci is now failing... because of the note in the commit: I am sure the test runner doesn't have permissions to create or delete these interfaces.

Yep probably. Anyway, I will add my own testing to this using Nispor. Thanks!

**Comment by little-dude** [comment]
@ffmancera @benjumanji what's the status on this?

**Comment by ffmancera** [comment]
@little-dude This weekend I will open a PR with wireguard full support. Sorry for the delay! :-)

**Comment by little-dude** [comment]
No problem :) I was just checking whether we should merge this or not.

**Comment by benjumanji** [comment]
Honestly at this point I'd like to pull the integration test that's breaking ci and just merge it. Using my own for for this patch is tiresome.

**Comment by little-dude** [comment]
Ok I'm going to fix the test and merge this then. I expect to make a release this weekend. Sorry for the delay @benjumanji

**Comment by benjumanji** [comment]
> Ok I'm going to fix the test and merge this then. I expect to make a release this weekend. Sorry for the delay @benjumanji

Np, I think there are some good intentions around making a more fully featured api, which I support, but I'd also prefer not to make perfect the enemy of good :D

**Comment by ffmancera** [comment]
> > Ok I'm going to fix the test and merge this then. I expect to make a release this weekend. Sorry for the delay @benjumanji
> 
> Np, I think there are some good intentions around making a more fully featured api, which I support, but I'd also prefer not to make perfect the enemy of good :D

I am very sorry for the delay. I got a lot of urgent stuff and couldn't finish the work here. I will extend the support later in another PR after this one got merged.

Again, I apologize and thanks for this contribution. :-)

**Comment by benjumanji** [comment]
> Again, I apologize and thanks for this contribution. :-)

Np, it happens. I look forward to seeing your work :)

**Comment by ousado** [comment]
Any news on this?

**Comment by benjumanji** [comment]
If you are blocked on this

```
async fn create_wg(handle: &mut LinkHandle, name: &str) -> Result<()> {
    let mut req = handle.add();
    let mutator = req.message_mut();
    mutator.header.flags &= !IFF_UP;
    mutator.header.change_mask &= !IFF_UP;
    mutator.nlas.push(Nla::Info(vec![Info::Kind(InfoKind::Other(
        "wireguard".to_owned(),
    ))]));
    mutator.nlas.push(Nla::IfName(name.to_owned()));
    req.execute()
        .await
        .with_context(|| format!("Failed to create {}", name))
}
```
will allow you to create a named interface while we wait :)

**Comment by little-dude** [comment]
Long overdue sorry. I'm going to merge this.

**Pull request merged**
