### PR TITLE
rtnetlink: support adding, getting and deleting route rules

### PR DESCRIPTION
**Pull request by ffmancera**
This patch is supporting add, del and get operations on route rules.

Signed-off-by: Fernando Fernandez Mancera <ffmancera@riseup.net>

### CODE REVIEW

**Review by little-dude — APPROVED** [review]
Thanks for the PR :)

I'm not familiar with `ip rule`, so I'm going to trust you regarding the ergonomics of these new methods. The code looks good do me otherwise :+1:

**Comment by ffmancera** [comment]
Thanks, for further testing I've integrated this with Nispor on https://github.com/nispor/nispor/pull/49

Are you planning to release soon? We need this on the next release in order to support it on Nispor. Thanks!

**Comment by little-dude** [comment]
I just published `rtnetlink` 0.5 with your changes :)

**Comment by ffmancera** [comment]
Thank you very much! That helps a lot :-)

**Pull request merged**
