### PR TITLE
Allow create DefaultNla

### PR DESCRIPTION
**Pull request by a1ien**

### CODE REVIEW

**Comment by wllenyj** [comment]
Why is this needed? Is there any background description?

**Comment by a1ien** [comment]
We want send custom message. For example `netlink_packet_route::rtnl::neighbour::NeighbourMessage`, we want create `netlink_packet_route::rtnl::neighbour::nlas::Nla` with Other variant

**Comment by cathay4t** [comment]
@a1ien We are in the middle of migrating to https://github.com/rust-netlink/netlink-packet-utils , could you create PR there again? Thank you!

**Comment by a1ien** [comment]
Done.

**Comment by cathay4t** [comment]
Closing as it is merged in https://github.com/rust-netlink/netlink-packet-utils/pull/4

**Pull request closed without merging**
