### PR TITLE
Implement additional link NLAs

### PR DESCRIPTION
**Pull request by TethysSvensson**
I have implemented 6 most recent NLAs, which brings netlink up-to-date with most recent linux kernel (both [the latest release][v5.9] and [master][linux-master] as of today).

[v5.9]: https://github.com/torvalds/linux/blob/v5.9/include/uapi/linux/if_link.h#L168
[linux-master]: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/uapi/linux/if_link.h?id=aae5ab854e38151e69f261dbf0e3b7e396403178#n337

I was unsure what to do about `IFLA_PROP_LIST` and `IFLA_PROTO_DOWN_REASON`, since they contain nested NLAs. I decided to do it in the same way as e.g. `IFLA_VF_PORTS`, which is just put into a `Vec<u8>` right now.

I also was a bit confused about why e.g. `IFLA_WEIGHT` is handled as a `Vec<u8>` and not a `u32`. Is there a reason for that? Should I perhaps also put `IFLA_MIN_MTU` and `IFLA_MAX_MTU` into `Vec<u8>`?

### CODE REVIEW

**Comment by little-dude** [comment]
Hi @TethysSvensson 

Thanks for the PR!

> I was unsure what to do about `IFLA_PROP_LIST` and `IFLA_PROTO_DOWN_REASON`, since they contain nested NLAs. I decided to do it in the same way as e.g. `IFLA_VF_PORTS`, which is just put into a `Vec<u8>` right now.

This is the right thing to do indeed.

> I also was a bit confused about why e.g. IFLA_WEIGHT is handled as a `Vec<u8>` and not a `u32`. Is there a reason for that? 

This is just because I haven't looked up the attribute so I didn't realize it was an `u32`. By default, I parse the attributes as `Vec<u8>`. PRs to parse these attributes are welcome.

**Review by little-dude — COMMENTED** [review]
The code looks good :) would you mind documenting the attributes you're adding since there are not too many? I know the crate is currently vastly under-documented but it's a problem I'd like to start addressing incrementally (see https://github.com/little-dude/netlink/issues/107)

**Comment by TethysSvensson** [comment]
@little-dude Done. Let me know if you want me to squash the commits.

**Comment by little-dude** [comment]
That's fine, thank you! Do you need a release for this?

**Comment by TethysSvensson** [comment]
Yes, a release would be nice, since I would like to start using `IFLA_PERM_ADDRESS`.

**Comment by TethysSvensson** [comment]
@little-dude I just saw that you added @ffmancera as a maintainer. Does this mean that you are no longer up for doing a release?

**Pull request merged**
