### PR TITLE
Fix nla emission in neighbour message

### PR DESCRIPTION
**Pull request by benjumanji**
Slice dst buffer to avoid overwriting the header.

### CODE REVIEW

**Comment by benjumanji** [comment]
fixes #71

**Comment by little-dude** [comment]
Thank you very much for the fix, the tests and the documentation :) Do you want me to make a release with the fix?

**Comment by benjumanji** [comment]
Sure that'd be great!

**Comment by little-dude** [comment]
Ok, 0.2.1 has been release :)

**Pull request merged**
